
/* app参数表 存放全局属性*/
CREATE TABLE IF NOT EXISTS APP_PARAMETER(
   PARAMETER_KEY     VARCHAR(50)   NOT NULL,   /* 参数键 */
   PARAMETER_VALUE   VARCHAR(150)  NOT NULL,   /* 参数值 */
   PARAMETER_EXPLAIN VARCHAR(150),             /* 参数说明 */
   PRIMARY KEY (PARAMETER_KEY)
);

/* 出租类型表 */
CREATE TABLE IF NOT EXISTS RENT_TYPE(
   RENT_TYPE_ID    TINYINT(1)  NOT NULL,  /* 出租类型id */
   RENT_TYPE_NAME  VARCHAR(10) NOT NULL,  /* 出租类型名称 */
   PRIMARY KEY (RENT_TYPE_ID)
);

/* 厂房业主类型型表 */
CREATE TABLE IF NOT EXISTS OWNER_TYPE(
   OWNER_TYPE_ID   TINYINT(1)  NOT NULL,  /* 业主类型id */
   OWNER_TYPE_NAME VARCHAR(10) NOT NULL,  /* 类型名称 */
   PRIMARY KEY (OWNER_TYPE_ID)
);

/* 厂房配套设施表 */
CREATE TABLE IF NOT EXISTS SUPPORTING_FACILITIES(
   FACILITIES_ID    TINYINT(1)  NOT NULL,  /* 设施id */
   FACILITIES_TYPE  TINYINT(1)  NOT NULL,  /* 设施信息类型 0:厂房  1:土地  2:租房 */
   FACILITIES_NAME  VARCHAR(20) NOT NULL,  /* 设施名称 */
   PRIMARY KEY (FACILITIES_ID)
);

/* 所在楼层表 */
CREATE TABLE FLOOR_POS(
   POS_ID      TINYINT(1)  NOT NULL,  /* 楼层位置id */
   POS_ID_NAME VARCHAR(20) NOT NULL,  /* 楼层位置说明 */
   PRIMARY KEY (POS_ID)
);

/* 楼层结构表 */
CREATE TABLE FLOOR_STRUCT(
   STRUCT_ID      TINYINT(1)  NOT NULL,  /* 楼层结构id */
   STRUCT_ID_NAME VARCHAR(20) NOT NULL,  /* 楼层结构名称 */
   PRIMARY KEY (STRUCT_ID)
);

/* 所有权表 */
CREATE TABLE IF NOT EXISTS OWNERSHIP(
   OWNERSHIP_ID    INT(11)     NOT NULL,  /* 所有权表 */
   OWNERSHIP_NAME  VARCHAR(20) NOT NULL,  /* 所有权名称 */
   PRIMARY KEY (OWNERSHIP_ID)
);

/* 土地用途表 */
CREATE TABLE IF NOT EXISTS PURPOSE(
   PURPOSE_ID    INT(11)     NOT NULL,  /* 用途id */
   PURPOSE_NAME  VARCHAR(20) NOT NULL,  /* 用途名称 */
   PRIMARY KEY (PURPOSE_ID)
);

/* 标签表 */
CREATE TABLE IF NOT EXISTS ATTRIBUTE_TAG(
   TAG_ID     TINYINT(1)   NOT NULL,  /* 标签ID */
   TAG_TYPE   TINYINT(1)   NOT NULL,  /* 标签类型 */
   TAG_NAME   VARCHAR(50)  NOT NULL,  /* 标签说明 */
   PRIMARY KEY (TAG_ID)
);

/* 装修类型表 */
CREATE TABLE IF NOT EXISTS FITMENT_TYPE(
   FITMENT_TYPE_ID    TINYINT(1)   NOT NULL,  /* 装修类型id */
   FITMENT_TYPE_NAME  VARCHAR(20)  NOT NULL,  /* 装修类型名称 */
   PRIMARY KEY (FITMENT_TYPE_ID)
);

/* 卫生间类型表 */
CREATE TABLE IF NOT EXISTS TOILET_TYPE(
   TOILET_TYPE_ID     TINYINT(1)   NOT NULL,  /* 卫生间类型id */
   TOILET_TYPE_NAME   VARCHAR(20)  NOT NULL,  /* 卫生间类型名称 */
   PRIMARY KEY (TOILET_TYPE_ID)
);

/* 资讯功能表 */
CREATE TABLE IF NOT EXISTS INFORMATION_FUNCTION(
   FUN_INDEX      TINYINT(2)   NOT NULL,    /* 资讯功能索引 */
   FUN_EXPLAIN    VARCHAR(150) NOT NULL,    /* 资讯功能名称 */
   PRIMARY KEY (FUN_INDEX)
);

/* 搜索表 */
CREATE TABLE IF NOT EXISTS SEARCH(
   SEARCH_ID             TINYINT(3)  NOT NULL,   /* 搜索id */
   SEARCH_TYPE           TINYINT(3)  NOT NULL,   /* 0:面积 1:租金 2:楼层 3:结构 4:标签 5:区域 6:房型 7:排序 8:设施 */
   SEARCH_TYPE_NAME      VARCHAR(50) NOT NULL,   /* 搜索类型名称 */
   SEARCH_COME           TINYINT(3)  NOT NULL,   /* 1:厂房 2:土地 3:租房 */
   PRIMARY KEY (SEARCH_ID,SEARCH_TYPE,SEARCH_COME)
);

/* 分店列表 */
CREATE TABLE IF NOT EXISTS FACTORY_BRANCH(
   BRANCH_INDEX  TINYINT(3)   NOT NULL,  /* 分店索引排序 */
   BRANCH_URL    VARCHAR(150),           /* 分店图片url */
   AREA_CODE     VARCHAR(20)  NOT NULL,  /* 镇街编号 */
   BRANCH_NAME   VARCHAR(20)  NOT NULL,  /* 分店名称 */
   PRIMARY KEY (AREA_CODE)
);

/* 厂房适用行业表 */
CREATE TABLE IF NOT EXISTS APPLY_TRADE(
   TRADE_ID   TINYINT(1)  NOT NULL,  /* 行业id */
   TRADE_NAME VARCHAR(20) NOT NULL,  /* 行业名称 */
   PRIMARY KEY (TRADE_ID)
);

/* 房屋类型表 */
CREATE TABLE IF NOT EXISTS HOUSE_TYPE(
   HOUSE_TYPE_ID     TINYINT(1)   NOT NULL,  /* 房屋类型id */
   HOUSE_TYPE_NAME   VARCHAR(20)  NOT NULL,  /* 房屋类型名称 */
   PRIMARY KEY (HOUSE_TYPE_ID)
);

/* app全局的滚动翻页url表 */
CREATE TABLE IF NOT EXISTS APP_GLOBAL_PAGE(
   PAGE_INDEX    TINYINT(1)    NOT NULL,  /* 索引用于排序 */
   PAGE_URL      VARCHAR(150)  NOT NULL,  /* 图片url */   
   PAGE_TYPE     VARCHAR(150)  NOT NULL,  /* 0:主页 1:引导页 2.资讯排行榜 */
   PAGE_EXPLAIN  LONGTEXT,                /* 说明 */
   PRIMARY KEY (PAGE_INDEX,PAGE_TYPE)
);

/* 厂房用户信息表 */
CREATE TABLE IF NOT EXISTS FACTORY_USER(
   USER_TOKEN   VARCHAR(50)   NOT NULL,   /* 用户token */
   INTEGRAL     BIGINT(20)    DEFAULT 0,  /* 用户积分 */
   BROKERAGE    DECIMAL(10,2) DEFAULT 0,  /* 用户拥金 */
   PHONE_NUM    VARCHAR(11)   NOT NULL,   /* 用户id(手机号) */
   DEVICE_ID    VARCHAR(50),              /* 设备id */
   AVATAR_URL   VARCHAR(150),             /* 头像url */
   TAG          VARCHAR(150),             /* 用户个人标签 */
   GEOHASH      VARCHAR(30),              /* 个人经伟度 */
   USER_TYPE    TINYINT(1)    DEFAULT 0,  /* 用户类型 0:普通  1:业主 2.经纪人(从业主升级) */
   AUTH_TYPE    TINYINT(3)    DEFAULT 0,  /* 0:所有  使用2进制 */
   VERSION      TINYINT(3)    DEFAULT 0,  /* 数据版本 */
   PRIMARY KEY (USER_TOKEN)
);

/* 经纪人表 */
CREATE TABLE IF NOT EXISTS BROKER_USER(
   USER_TOKEN     VARCHAR(50)   NOT NULL,   /* 用户token */
   AREA_CODE      VARCHAR(20)   NOT NULL,   /* 所在镇街编号 */
   AVATAR_URL     VARCHAR(150),             /* 头像url */
   EXPERIENCE     DECIMAL(3,1)  NOT NULL,   /* 入行年份 */
   PUBLISH_COUNT  BIGINT(20)    DEFAULT 0,  /* 成交次数(经纪人排序) */
   PRIMARY KEY (USER_TOKEN)
);

/* 厂房信息表 */
CREATE TABLE IF NOT EXISTS INFO_FACTORY(
   FACTORY_ID         INT(11)         NOT NULL,      /* 厂房信息id */
   USER_TOKEN         VARCHAR(50)     NOT NULL,      /* 用户token */
   TITLE              VARCHAR(100)    NOT NULL,      /* 厂房标题 */
   SELLING_POINT      LONGTEXT        NOT NULL,      /* 厂房卖点 */

   AREA_CODE          VARCHAR(20)     NOT NULL,       /* 镇街编号 */
   ADDRESS            VARCHAR(150)    NOT NULL,       /* 镇街地址 */
   
   TOTAL_AREA         INT(11)         NOT NULL,       /* 出租总面积 */
   OFFICE_AREA        INT(11)         DEFAULT 0,      /* 办公室面积 */
   DORM_AREA          INT(11)         DEFAULT 0,      /* 宿舍面积 */
   
   FACTORY_TYPE       TINYINT(1) DEFAULT 0 NOT NULL,  /* 厂房类型 0:普通厂房 1:优质厂房 2:精品厂房 */
   RENT_TYPE_ID       TINYINT(1) DEFAULT 0 NOT NULL,  /* 出租类型id */
   RENT_MODE_ID       TINYINT(1) DEFAULT 0 NOT NULL,  /* 租售方式id */
   OWNER_TYPE_ID      TINYINT(1) DEFAULT 0 NOT NULL,  /* 业主类型id */
   STRUCT_ID          TINYINT(1) DEFAULT 1 NOT NULL,  /* 楼层结构id 默认 1:标准厂房 */
   FLOOR_HIGHT        VARCHAR(100),                   /* 楼层高度 */
   PHONE_NUM          VARCHAR(11)          NOT NULL,  /* 联系电话 */
   CONTACTS           VARCHAR(100)         NOT NULL,  /* 联系人 */
   
   FOREGIFT_ID        TINYINT(1) DEFAULT 0 NOT NULL,  /* 押金id 默认 0:一押一付 */     
   NEWOLD_ID          TINYINT(1) DEFAULT 0 NOT NULL,  /* 新旧程度id 默认 0:全新 */   
   IS_UP_SHELVES      TINYINT(1) DEFAULT 0,           /* 是否上架 0:下架 1:上架(有效时间) */ 
   CANTEEN            TINYINT(1) DEFAULT 0,           /* 食堂 0:没有 1:公有 2:私有 */
   IS_ELEVATOR        TINYINT(1) DEFAULT 1,           /* 是否有电梯 0:没有 1:有 */
   IS_FIRE_PROTECTION TINYINT(1) DEFAULT 1,           /* 是否消防护 0:没有 1:有 */
   GREEN_CARD         TINYINT(1) DEFAULT 1,           /* 环保证 0:无 1:有 2:可办 */
   FLOOR_POS_ID       TINYINT(1) DEFAULT 0,           /* 所在楼层 默认 0:其他 */

   ENJOY              INT(11)   DEFAULT 0  NOT NULL,  /* 悬赏租金 分为单位 */
   PRICE              INT(11)   DEFAULT 0  NOT NULL,  /* 厂房租金 分为单位 */
   DISTRIBUTION       INT(11)   NOT NULL,             /* 配电量 */

   THUMBNAILS         VARCHAR(150),                   /* 缩略图集对应信息图片表 逗号隔开 如: 1,2,3 */
   TAGS               VARCHAR(150),                   /* 属性标签对应标签表 逗号隔开 如: 1,4,5 */
   FACILITIES         VARCHAR(150),                   /* 配套设施对应设施表 逗号隔开 如: 1,4, */
   TRADES             VARCHAR(150),                   /* 适用行业对应行业表 逗号隔开 如: 1,4, */
   GEOHASH            VARCHAR(30),                    /* 厂房经伟度 */
   
   PANORAMA_URL       VARCHAR(150),                   /* 全景周边视频url */
   FACTORY_CODE       VARCHAR(30),                    /* 厂房编号 */

   BROWSE_COUNT       INT(10)       DEFAULT 0,        /* 总浏览数 */
   CREATE_TIME        VARCHAR(14)   NOT NULL,         /* 创建时间 */
   UPDATE_DATE        VARCHAR(14),                    /* 更新时间 */
   VERSION            TINYINT(3)    DEFAULT 0,        /* 数据版本 */
   PRIMARY KEY (FACTORY_ID)
);

/* 厂房图片表 */
CREATE TABLE IF NOT EXISTS PHOTO_FACTORY(
   PHOTO_ID   INT(11)      NOT NULL,  /* 信息自增id */
   PHOTO_URL  VARCHAR(150) NOT NULL,   /* 信息图片 */
   VERSION    TINYINT(3)   DEFAULT 0,  /* 数据版本 */
   PRIMARY KEY (PHOTO_ID)
);

/* 厂房预约 */
CREATE TABLE IF NOT EXISTS FACTORY_BOOK(
   USER_TOKEN     VARCHAR(50)   NOT NULL,    /* 用户token */
   BOOK_DAY       TINYINT(3),                /* 当前预约天数 */
   BOOK_EXPLAIN   LONGTEXT,                  /* 预订说明 */
   MATCHING       TINYINT(3)    DEFAULT 0,   /* 匹配结果 0:匹配中 1:匹配完成 2:匹配失败 */
   PHONE_NUM      VARCHAR(11)   NOT NULL,    /* 联系电话 */
   CONTACTS       VARCHAR(100)  NOT NULL,    /* 联系人 */
   CREATE_TIME    VARCHAR(14)   NOT NULL,    /* 创建时间 */
   VERSION        TINYINT(3)    DEFAULT 0,   /* 数据版本 */
   PRIMARY KEY (USER_TOKEN,CREATE_TIME)
);

/* 厂房信息记录表 */
CREATE TABLE IF NOT EXISTS FACTORY_RECORD(
   USER_TOKEN   VARCHAR(50) NOT NULL,    /* 用户token */
   RECORD_ID    INT(11)     NOT NULL,    /* 记录id(根据类型来信息表) */
   RECORD_TYPE  TINYINT(1)  DEFAULT 0,   /* 厂房记录类型 0:厂房收藏  1:土地历史 2:租房收藏 3:浏览厂房 */
   CREATE_TIME  VARCHAR(14) NOT NULL,    /* 创建时间 */
   PRIMARY KEY (USER_TOKEN,RECORD_TYPE,RECORD_ID)
);

/* 资讯行情表 */
CREATE TABLE IF NOT EXISTS INFORMATION_MARKET(
   TITLE        VARCHAR(150)  NOT NULL,   /* 标题 */
   TITLE_URL    VARCHAR(150),             /* 标题图片url */
   CLICK_URL    VARCHAR(150),             /* 点击跳转的url */
   BROWSE_COUNT INT(11)       DEFAULT 0,  /* 总浏览数 */
   CREATE_TIME  VARCHAR(14)   NOT NULL,   /* 创建时间 */
   CONTENT      LONGTEXT,                 /* 内容可以html */
   PRIMARY KEY (CREATE_TIME)
);

/* 资讯 fm url 表 */
CREATE TABLE IF NOT EXISTS INFORMATION_FM(
   FM_INDEX         TINYINT(1)    NOT NULL,  /* 索引用于排序 */
   FM_SOUND_URL     VARCHAR(150)  NOT NULL,  /* fm url */
   FM_PICS_URL      VARCHAR(150)  NOT NULL,  /* 图片url */   
   CITY_CODE        VARCHAR(20)   NOT NULL,  /* 城市编号 */
   FM_EXPLAIN       LONGTEXT ,               /* 说明 */
   PRIMARY KEY (CITY_CODE)
);

/* 资讯FM收藏表 */
CREATE TABLE IF NOT EXISTS INFORMATION_FM_COLLECT(
   USER_TOKEN    VARCHAR(50)   NOT NULL,   /* 用户token */
   CITY_CODE     VARCHAR(20)   NOT NULL,  /* 城市编号 */
   CREATE_TIME   VARCHAR(14)   NOT NULL,  /* 收藏时间 */
   PRIMARY KEY (USER_TOKEN,CITY_CODE)
);

/* 动态图片表 */
CREATE TABLE IF NOT EXISTS PHOTO_DYNAMIC(
   PHOTO_ID   INT(11)      NOT NULL,   /* 信息自增id */
   PHOTO_URL  VARCHAR(150) NOT NULL,   /* 信息图片 */
   VERSION    TINYINT(3)   DEFAULT 0,  /* 数据版本 */
   PRIMARY KEY (PHOTO_ID)
);

/* 新旧程序表 */
CREATE TABLE NEWOLD_DEGREE(
   DEGREE_ID    TINYINT(1)  NOT NULL,   /* 程度id */
   DEGREE_NAME  VARCHAR(50) NOT NULL,   /* 新旧描述 */
   PRIMARY KEY (DEGREE_ID)
);

/* 押金类型 表 */
CREATE TABLE FOREGIFT_TYPE(
   FOREGIFT_ID      TINYINT(1)  NOT NULL,   /* 押金类型id */
   FOREGIFT_NAME    VARCHAR(50) NOT NULL,   /* 押金类型说明 */
   PRIMARY KEY (FOREGIFT_ID)
);

/* 举报说明表 */
CREATE TABLE REPORT_EXPLAIN(
   EXPLAIN_INDEX  TINYINT(1)   NOT NULL,  /* 说明索引 */
   EXPLAIN_TEXT   VARCHAR(100) NOT NULL,  /* 说明 */
   PRIMARY KEY (EXPLAIN_INDEX)
);

/* 手机号码前缀表 */
CREATE TABLE PHONE_PREFIX(
   PREFIX_CODE     VARCHAR(3)  NOT NULL,  /* 手机号前缀*/
   PRIMARY KEY (PREFIX_CODE)
);

DELETE FROM APP_PARAMETER;
DELETE FROM RENT_TYPE;
DELETE FROM OWNER_TYPE;
DELETE FROM SUPPORTING_FACILITIES;
DELETE FROM FLOOR_POS;
DELETE FROM FLOOR_STRUCT;
DELETE FROM OWNERSHIP;
DELETE FROM FACTORY_BRANCH;
DELETE FROM PURPOSE;
DELETE FROM ATTRIBUTE_TAG;
DELETE FROM HOUSE_TYPE;
DELETE FROM FITMENT_TYPE;
DELETE FROM TOILET_TYPE;
DELETE FROM SEARCH;
DELETE FROM INFORMATION_FUNCTION;
DELETE FROM RENT_MODE;
DELETE FROM NEWOLD_DEGREE;
DELETE FROM APPLY_TRADE;
DELETE FROM FOREGIFT_TYPE;
DELETE FROM REPORT_EXPLAIN;
DELETE FROM SEARCH;
DELETE FROM PHONE_PREFIX;

INSERT INTO APP_PARAMETER (PARAMETER_KEY,PARAMETER_VALUE,PARAMETER_EXPLAIN) VALUES ('FACTORY_MAX_PAGE',           '5',            '最大图片显示张数');
INSERT INTO APP_PARAMETER (PARAMETER_KEY,PARAMETER_VALUE,PARAMETER_EXPLAIN) VALUES ('FACILITIES_MAX_NUM',         '4',            '配套设施最大数');
INSERT INTO APP_PARAMETER (PARAMETER_KEY,PARAMETER_VALUE,PARAMETER_EXPLAIN) VALUES ('TAG_MAX_NUM',                '10',           '标签最大数');
INSERT INTO APP_PARAMETER (PARAMETER_KEY,PARAMETER_VALUE,PARAMETER_EXPLAIN) VALUES ('TRADE_MAX_NUM',              '10',           '适应行业最大数');
INSERT INTO APP_PARAMETER (PARAMETER_KEY,PARAMETER_VALUE,PARAMETER_EXPLAIN) VALUES ('FACTORY_VALID_TIME',         '15',           '厂房信息有效时间(天)');
INSERT INTO APP_PARAMETER (PARAMETER_KEY,PARAMETER_VALUE,PARAMETER_EXPLAIN) VALUES ('FACTORY_BOOK_MAX_TIME',      '180',          '厂房最大预订时间(天)');
INSERT INTO APP_PARAMETER (PARAMETER_KEY,PARAMETER_VALUE,PARAMETER_EXPLAIN) VALUES ('FACTORY_BOOK_MAX_TEXT',      '400',          '厂房最大预最大文字数');
INSERT INTO APP_PARAMETER (PARAMETER_KEY,PARAMETER_VALUE,PARAMETER_EXPLAIN) VALUES ('GEOGRAPHY_MAX_RANGE',        '1',            '地理位置最大半径(km)');
INSERT INTO APP_PARAMETER (PARAMETER_KEY,PARAMETER_VALUE,PARAMETER_EXPLAIN) VALUES ('AGREEMENT',                  'http://',      '使用协义');
INSERT INTO APP_PARAMETER (PARAMETER_KEY,PARAMETER_VALUE,PARAMETER_EXPLAIN) VALUES ('FACTORY_INFO_MAX_NUM',       '10',           '一次取厂房详情最大条数');
INSERT INTO APP_PARAMETER (PARAMETER_KEY,PARAMETER_VALUE,PARAMETER_EXPLAIN) VALUES ('FACTORY_MASTERWORK_MAX_NUM', '5',            '一次取精品厂房详情最大条数');
INSERT INTO APP_PARAMETER (PARAMETER_KEY,PARAMETER_VALUE,PARAMETER_EXPLAIN) VALUES ('FACTORY_SAVANT_MAX_NUM',     '5',            '一次取分店最大条数');
INSERT INTO APP_PARAMETER (PARAMETER_KEY,PARAMETER_VALUE,PARAMETER_EXPLAIN) VALUES ('BROKER_MAX_NUM',             '3',            '经纪人排序显示最大数');
INSERT INTO APP_PARAMETER (PARAMETER_KEY,PARAMETER_VALUE,PARAMETER_EXPLAIN) VALUES ('BROKER_USER_MAX_NUM',        '10',           '分店经纪人显示最大数');
INSERT INTO APP_PARAMETER (PARAMETER_KEY,PARAMETER_VALUE,PARAMETER_EXPLAIN) VALUES ('USER_PWD_NUM',               '6',            '用户密码长度');
INSERT INTO APP_PARAMETER (PARAMETER_KEY,PARAMETER_VALUE,PARAMETER_EXPLAIN) VALUES ('TOKEN_VALID_TIMR',           '7',            '用户token有效时间(天)');
INSERT INTO APP_PARAMETER (PARAMETER_KEY,PARAMETER_VALUE,PARAMETER_EXPLAIN) VALUES ('LIMIT_STRING',         'Pz48JyI6e30sXC9bXQ==','限制使用的字符base64,因为josn不能直接读取');

/* 验证码参数 */
INSERT INTO APP_PARAMETER (PARAMETER_KEY,PARAMETER_VALUE,PARAMETER_EXPLAIN) VALUES ('VERIFY_VALID_TIME',         '2',               '发送验证码的时间长(分钟)');
INSERT INTO APP_PARAMETER (PARAMETER_KEY,PARAMETER_VALUE,PARAMETER_EXPLAIN) VALUES ('USER_DEFAULT_PWD',          '123456',          '默认密码');


/* 手机号码前缀 */
INSERT INTO PHONE_PREFIX (PREFIX_CODE) VALUES ('130'),('131'),('132'),('133'),('134'),('135'),('136'),('137'),('138'),('139'),('150'),('151'),('152'),('153'),
                                              ('156'),('158'),('159'),('170'),('175'),('176'),('177'),('178'),('183'),('182'),('185'),('186'),('188'),('189');



/* ===================  基本已定义 ==================== */
/* 出租方式表 */
INSERT INTO RENT_TYPE (RENT_TYPE_ID,RENT_TYPE_NAME) VALUES ('0','整租');
INSERT INTO RENT_TYPE (RENT_TYPE_ID,RENT_TYPE_NAME) VALUES ('1','分租');

/* 租售方式 */
INSERT INTO RENT_MODE (RENT_MODE_ID,RENT_MODE_NAME) VALUES ('0','出租');
INSERT INTO RENT_MODE (RENT_MODE_ID,RENT_MODE_NAME) VALUES ('1','出售');
INSERT INTO RENT_MODE (RENT_MODE_ID,RENT_MODE_NAME) VALUES ('2','可租可售');

/* 厂房业主类型 */
INSERT INTO OWNER_TYPE (OWNER_TYPE_ID,OWNER_TYPE_NAME) VALUES ('0','业主');
INSERT INTO OWNER_TYPE (OWNER_TYPE_ID,OWNER_TYPE_NAME) VALUES ('1','村委会');
INSERT INTO OWNER_TYPE (OWNER_TYPE_ID,OWNER_TYPE_NAME) VALUES ('2','镇政府');
INSERT INTO OWNER_TYPE (OWNER_TYPE_ID,OWNER_TYPE_NAME) VALUES ('3','区政府');
INSERT INTO OWNER_TYPE (OWNER_TYPE_ID,OWNER_TYPE_NAME) VALUES ('4','市政府');
INSERT INTO OWNER_TYPE (OWNER_TYPE_ID,OWNER_TYPE_NAME) VALUES ('5','经纪人');

/* 配套设施 */
INSERT INTO SUPPORTING_FACILITIES (FACILITIES_ID,FACILITIES_TYPE,FACILITIES_NAME) VALUES ('0','0','其他');
INSERT INTO SUPPORTING_FACILITIES (FACILITIES_ID,FACILITIES_TYPE,FACILITIES_NAME) VALUES ('1','0','停车场');
INSERT INTO SUPPORTING_FACILITIES (FACILITIES_ID,FACILITIES_TYPE,FACILITIES_NAME) VALUES ('2','0','蓝球场');
INSERT INTO SUPPORTING_FACILITIES (FACILITIES_ID,FACILITIES_TYPE,FACILITIES_NAME) VALUES ('3','0','图书管');
INSERT INTO SUPPORTING_FACILITIES (FACILITIES_ID,FACILITIES_TYPE,FACILITIES_NAME) VALUES ('4','0','键身中心');
INSERT INTO SUPPORTING_FACILITIES (FACILITIES_ID,FACILITIES_TYPE,FACILITIES_NAME) VALUES ('5','0','超市');
INSERT INTO SUPPORTING_FACILITIES (FACILITIES_ID,FACILITIES_TYPE,FACILITIES_NAME) VALUES ('6','0','党员活动中心');
INSERT INTO SUPPORTING_FACILITIES (FACILITIES_ID,FACILITIES_TYPE,FACILITIES_NAME) VALUES ('7','0','咖啡厅');

/* 所在楼层 */
INSERT INTO FLOOR_POS (POS_ID,POS_ID_NAME) VALUES ('0','其他');
INSERT INTO FLOOR_POS (POS_ID,POS_ID_NAME) VALUES ('1','一楼');
INSERT INTO FLOOR_POS (POS_ID,POS_ID_NAME) VALUES ('2','二楼以上');
INSERT INTO FLOOR_POS (POS_ID,POS_ID_NAME) VALUES ('3','独栋');
INSERT INTO FLOOR_POS (POS_ID,POS_ID_NAME) VALUES ('4','独院');

/* 楼层结构表 */
INSERT INTO FLOOR_STRUCT (STRUCT_ID,STRUCT_ID_NAME) VALUES ('0','其他');
INSERT INTO FLOOR_STRUCT (STRUCT_ID,STRUCT_ID_NAME) VALUES ('1','标准厂房');
INSERT INTO FLOOR_STRUCT (STRUCT_ID,STRUCT_ID_NAME) VALUES ('2','简易厂房');
INSERT INTO FLOOR_STRUCT (STRUCT_ID,STRUCT_ID_NAME) VALUES ('3','钢结构');

/* 所有权类型 */
INSERT INTO OWNERSHIP (OWNERSHIP_ID,OWNERSHIP_NAME) VALUES ('0','集体');
INSERT INTO OWNERSHIP (OWNERSHIP_ID,OWNERSHIP_NAME) VALUES ('1','个人');

/* 用途 */
INSERT INTO PURPOSE (PURPOSE_ID,PURPOSE_NAME) VALUES ('0','住宅用地');
INSERT INTO PURPOSE (PURPOSE_ID,PURPOSE_NAME) VALUES ('1','工业用地');

/* 属性标签 */
INSERT INTO ATTRIBUTE_TAG (TAG_ID,TAG_TYPE,TAG_NAME) VALUES ('0', '0','小面积');
INSERT INTO ATTRIBUTE_TAG (TAG_ID,TAG_TYPE,TAG_NAME) VALUES ('1', '0','大面积');
INSERT INTO ATTRIBUTE_TAG (TAG_ID,TAG_TYPE,TAG_NAME) VALUES ('2', '0','楼层多');
INSERT INTO ATTRIBUTE_TAG (TAG_ID,TAG_TYPE,TAG_NAME) VALUES ('3', '0','独院');
INSERT INTO ATTRIBUTE_TAG (TAG_ID,TAG_TYPE,TAG_NAME) VALUES ('4', '0','环境好');
INSERT INTO ATTRIBUTE_TAG (TAG_ID,TAG_TYPE,TAG_NAME) VALUES ('5', '0','带装修');
INSERT INTO ATTRIBUTE_TAG (TAG_ID,TAG_TYPE,TAG_NAME) VALUES ('6', '0','带办公');
INSERT INTO ATTRIBUTE_TAG (TAG_ID,TAG_TYPE,TAG_NAME) VALUES ('7', '0','原房东');
INSERT INTO ATTRIBUTE_TAG (TAG_ID,TAG_TYPE,TAG_NAME) VALUES ('8', '0','一楼');
INSERT INTO ATTRIBUTE_TAG (TAG_ID,TAG_TYPE,TAG_NAME) VALUES ('9', '0','带宿舍');
INSERT INTO ATTRIBUTE_TAG (TAG_ID,TAG_TYPE,TAG_NAME) VALUES ('10', '0','新建房');
INSERT INTO ATTRIBUTE_TAG (TAG_ID,TAG_TYPE,TAG_NAME) VALUES ('11', '0','标准型');
INSERT INTO ATTRIBUTE_TAG (TAG_ID,TAG_TYPE,TAG_NAME) VALUES ('12', '0','钢构型');
INSERT INTO ATTRIBUTE_TAG (TAG_ID,TAG_TYPE,TAG_NAME) VALUES ('13', '0','位置好');
INSERT INTO ATTRIBUTE_TAG (TAG_ID,TAG_TYPE,TAG_NAME) VALUES ('14', '0','低价');

/* 装修类型 */
INSERT INTO FITMENT_TYPE (FITMENT_TYPE_ID,FITMENT_TYPE_NAME) VALUES ('0','简单装修');
INSERT INTO FITMENT_TYPE (FITMENT_TYPE_ID,FITMENT_TYPE_NAME) VALUES ('1','精装修');

/* 卫生间类型 */
INSERT INTO TOILET_TYPE (TOILET_TYPE_ID,TOILET_TYPE_NAME) VALUES ('0','公用');
INSERT INTO TOILET_TYPE (TOILET_TYPE_ID,TOILET_TYPE_NAME) VALUES ('1','独立');

/* 资讯功能表 */
INSERT INTO INFORMATION_FUNCTION (FUN_INDEX,FUN_EXPLAIN) VALUES ('0','FM');
INSERT INTO INFORMATION_FUNCTION (FUN_INDEX,FUN_EXPLAIN) VALUES ('1','推荐');
INSERT INTO INFORMATION_FUNCTION (FUN_INDEX,FUN_EXPLAIN) VALUES ('2','行情');
INSERT INTO INFORMATION_FUNCTION (FUN_INDEX,FUN_EXPLAIN) VALUES ('3','排行榜');
INSERT INTO INFORMATION_FUNCTION (FUN_INDEX,FUN_EXPLAIN) VALUES ('4','小视频');
INSERT INTO INFORMATION_FUNCTION (FUN_INDEX,FUN_EXPLAIN) VALUES ('5','附近');

/* 搜索条件表 */
INSERT INTO SEARCH (SEARCH_COME,SEARCH_TYPE,SEARCH_TYPE_NAME,JUDGE_TYPE,JUDGE_FIELD) VALUES ('0','1','面积','1','TOTAL_AREA');
INSERT INTO SEARCH (SEARCH_COME,SEARCH_TYPE,SEARCH_TYPE_NAME,JUDGE_TYPE,JUDGE_FIELD) VALUES ('0','2','租金','1','PRICE');
INSERT INTO SEARCH (SEARCH_COME,SEARCH_TYPE,SEARCH_TYPE_NAME,JUDGE_TYPE,JUDGE_FIELD) VALUES ('0','3','楼层','2','FLOOR_POS_ID');
INSERT INTO SEARCH (SEARCH_COME,SEARCH_TYPE,SEARCH_TYPE_NAME,JUDGE_TYPE,JUDGE_FIELD) VALUES ('0','4','结构','2','STRUCT_ID');
INSERT INTO SEARCH (SEARCH_COME,SEARCH_TYPE,SEARCH_TYPE_NAME,JUDGE_TYPE,JUDGE_FIELD) VALUES ('0','5','标签','3','TAGS');
INSERT INTO SEARCH (SEARCH_COME,SEARCH_TYPE,SEARCH_TYPE_NAME,JUDGE_TYPE,JUDGE_FIELD) VALUES ('0','6','区域','4','AREA_CODE');
INSERT INTO SEARCH (SEARCH_COME,SEARCH_TYPE,SEARCH_TYPE_NAME,JUDGE_TYPE,JUDGE_FIELD) VALUES ('0','8','设施','3','FACILITIES');

/* 新旧程序 */
INSERT INTO NEWOLD_DEGREE (DEGREE_ID,DEGREE_NAME) VALUES ('1','全新');
INSERT INTO NEWOLD_DEGREE (DEGREE_ID,DEGREE_NAME) VALUES ('2','九成新');
INSERT INTO NEWOLD_DEGREE (DEGREE_ID,DEGREE_NAME) VALUES ('3','八成新');
INSERT INTO NEWOLD_DEGREE (DEGREE_ID,DEGREE_NAME) VALUES ('4','七成新');
INSERT INTO NEWOLD_DEGREE (DEGREE_ID,DEGREE_NAME) VALUES ('5','七以下');

/* 适用行业 */
INSERT INTO APPLY_TRADE (TRADE_ID,TRADE_NAME) VALUES ('0','其他');
INSERT INTO APPLY_TRADE (TRADE_ID,TRADE_NAME) VALUES ('1','医药卫生');
INSERT INTO APPLY_TRADE (TRADE_ID,TRADE_NAME) VALUES ('2','机械机电');
INSERT INTO APPLY_TRADE (TRADE_ID,TRADE_NAME) VALUES ('3','轻工食品');
INSERT INTO APPLY_TRADE (TRADE_ID,TRADE_NAME) VALUES ('4','服装纺织');
INSERT INTO APPLY_TRADE (TRADE_ID,TRADE_NAME) VALUES ('5','办公文教');
INSERT INTO APPLY_TRADE (TRADE_ID,TRADE_NAME) VALUES ('6','电子电工');
INSERT INTO APPLY_TRADE (TRADE_ID,TRADE_NAME) VALUES ('7','家居用品');

/* 押金类型 */
INSERT INTO FOREGIFT_TYPE (FOREGIFT_ID,FOREGIFT_NAME) VALUES ('1','一押一付');
INSERT INTO FOREGIFT_TYPE (FOREGIFT_ID,FOREGIFT_NAME) VALUES ('2','两押一付');
INSERT INTO FOREGIFT_TYPE (FOREGIFT_ID,FOREGIFT_NAME) VALUES ('3','三押一付');
INSERT INTO FOREGIFT_TYPE (FOREGIFT_ID,FOREGIFT_NAME) VALUES ('4','首交半年');
INSERT INTO FOREGIFT_TYPE (FOREGIFT_ID,FOREGIFT_NAME) VALUES ('5','首交一年');

/* 举报 */
INSERT INTO REPORT_EXPLAIN (EXPLAIN_INDEX,EXPLAIN_TEXT) VALUES ('0','其他');
INSERT INTO REPORT_EXPLAIN (EXPLAIN_INDEX,EXPLAIN_TEXT) VALUES ('1','厂房位置有误');
INSERT INTO REPORT_EXPLAIN (EXPLAIN_INDEX,EXPLAIN_TEXT) VALUES ('2','房源价格不符');
INSERT INTO REPORT_EXPLAIN (EXPLAIN_INDEX,EXPLAIN_TEXT) VALUES ('3','发布人电话有误');
INSERT INTO REPORT_EXPLAIN (EXPLAIN_INDEX,EXPLAIN_TEXT) VALUES ('4','图片或面积有误');

/* 房屋类 */
INSERT INTO HOUSE_TYPE (HOUSE_TYPE_ID,HOUSE_TYPE_NAME) VALUES ('0','2室2厅1卫');
INSERT INTO HOUSE_TYPE (HOUSE_TYPE_ID,HOUSE_TYPE_NAME) VALUES ('1','2厅1卫');